version: "3.7"
services:
  pr_checks:
    image: docker.io/grado/pdm:3.12-alpine
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      platforms:
        - linux/amd64
    entrypoint: /bin/sh
