name: Build and Publish

on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    container:
      image: docker.io/grado/pdm:3.12-alpine

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        run: pdm publish -u __token__ -P ${{ secrets.PYPI_API_TOKEN }}
