name: Check Changelog Updated

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate comparisons

      - name: Determine base branch
        run: |
          BASE_BRANCH=${{ github.base_ref }}
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

      - name: Fetch base branch (master or dev)
        run: |
          git fetch origin $BASE_BRANCH --depth=1

      - name: Check if changelog was updated
        run: |
          if git diff --name-only origin/$BASE_BRANCH HEAD | grep -q "docs/changelog.md"; then
            echo "✅ Changelog updated."
          else
            echo "❌ Changelog not updated. Please update docs/changelog.md."
            exit 1
          fi
