name: Run Tests on PR

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/grado/pdm:3.12-alpine

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pdm sync --clean

      - name: Lint
        run: |
          pdm run inv format --check

      - name: Run Tests
        run: |
          pdm run pytest tests
