name: Check Version Increment

on:
  pull_request:
    branches:
      - master

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for PR branch

      - name: Get version from PR branch
        id: pr_version
        run: |
          VERSION_FILE="src/loggerado/__init__.py"
          if [[ ! -f "$VERSION_FILE" ]]; then
            echo "Version file not found: $VERSION_FILE"
            exit 1
          fi
          PR_VERSION=$(grep -oP '(?<=__version__ = ")[^"]+' $VERSION_FILE)
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 1  # Shallow clone for master branch

      - name: Get version from master branch
        id: master_version
        run: |
          VERSION_FILE="src/loggerado/__init__.py"
          if [[ ! -f "$VERSION_FILE" ]]; then
            echo "Version file not found: $VERSION_FILE"
            exit 1
          fi
          MASTER_VERSION=$(grep -oP '(?<=__version__ = ")[^"]+' $VERSION_FILE)
          echo "MASTER_VERSION=$MASTER_VERSION" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          if [[ "$PR_VERSION" == "$MASTER_VERSION" ]]; then
            echo "❌ Version has not been incremented! PR Version: $PR_VERSION, Master Version: $MASTER_VERSION"
            exit 1
          else
            echo "✅ Version incremented: PR Version: $PR_VERSION, Master Version: $MASTER_VERSION"
          fi
